---
- name: Install k3s and configure kubeconfig
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Install k3s using official script
      ansible.builtin.shell: set -o pipefail && curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Ensure .k3s directory exists in home
      become: false
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/.k3s"
        state: directory
        mode: '0755'

    - name: Copy k3s.yaml to user's .k3s directory
      ansible.builtin.copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ lookup('env', 'HOME') }}/.k3s/k3s.yaml"
        remote_src: true
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"
        mode: '0644'

    - name: Set KUBECONFIG environment variable in .bashrc
      ansible.builtin.lineinfile:
        path: "{{ lookup('env', 'HOME') }}/.bashrc"
        line: 'export KUBECONFIG=$HOME/.k3s/k3s.yaml'
        state: present
      become: false

    - name: Enable kubectl autocompletion in .bashrc
      ansible.builtin.lineinfile:
        path: "{{ lookup('env', 'HOME') }}/.bashrc"
        line: 'source <(kubectl completion bash)'
        state: present
      become: false

    - name: Add kubectl alias to .bashrc
      ansible.builtin.lineinfile:
        path: "{{ lookup('env', 'HOME') }}/.bashrc"
        line: 'alias k=kubectl'
        state: present
      become: false

    - name: Add kubectl completion for alias k to .bashrc
      ansible.builtin.lineinfile:
        path: "{{ lookup('env', 'HOME') }}/.bashrc"
        line: 'complete -F __start_kubectl k'
        state: present
      become: false

    - name: Display all pods in all namespaces (if kubectl exists)
      ansible.builtin.shell: |
        if command -v kubectl >/dev/null 2>&1; then
          kubectl get pod -A
        else
          echo "kubectl not found, skipping pod display."
        fi
      environment:
        KUBECONFIG: "{{ lookup('env', 'HOME') }}/.k3s/k3s.yaml"
      register: pods_output
      changed_when: false

    - name: Install Helm using official script
      ansible.builtin.shell: set -o pipefail && curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: Add elastic Helm repo
      ansible.builtin.command: helm repo add elastic https://helm.elastic.co
      args:
        creates: "{{ lookup('env', 'HOME') }}/.cache/helm/repository/elastic-index.yaml"
      become: false
      environment:
        KUBECONFIG: "{{ lookup('env', 'HOME') }}/.k3s/k3s.yaml"

    - name: Update Helm repos
      ansible.builtin.command: helm repo update
      become: false
      changed_when: false
      environment:
        KUBECONFIG: "{{ lookup('env', 'HOME') }}/.k3s/k3s.yaml"
